import type { Key } from './hooks/useKeypress.js';

export const Command = {
  ESCAPE: 'escape',
  SUBMIT: 'submit',
  RETURN: 'return',
  NEWLINE: 'newline',
  CLEAR_SCREEN: 'clear_screen',
  CLEAR_INPUT: 'clear_input',
  HOME: 'home',
  END: 'end',
  NAVIGATION_UP: 'navigation_up',
  NAVIGATION_DOWN: 'navigation_down',
  HISTORY_UP: 'history_up',
  HISTORY_DOWN: 'history_down',
  COMPLETION_UP: 'completion_up',
  COMPLETION_DOWN: 'completion_down',
  ACCEPT_SUGGESTION: 'accept_suggestion',
  KILL_LINE_RIGHT: 'kill_line_right',
  KILL_LINE_LEFT: 'kill_line_left',
  OPEN_EXTERNAL_EDITOR: 'open_external_editor',
  PASTE_CLIPBOARD_IMAGE: 'paste_clipboard_image',
  REVERSE_SEARCH: 'reverse_search',
  ACCEPT_SUGGESTION_REVERSE_SEARCH: 'accept_suggestion_reverse_search',
  SUBMIT_REVERSE_SEARCH: 'submit_reverse_search',
} as const;

export const keyMatchers: Record<typeof Command[keyof typeof Command], (key: Key) => boolean> = {
  [Command.ESCAPE]: (key) => key.escape === true,
  [Command.SUBMIT]: (key) => key.return === true,
  [Command.RETURN]: (key) => key.return === true,
  [Command.NEWLINE]: (key) => key.ctrl === true && key.return === true,
  [Command.CLEAR_SCREEN]: (key) => key.ctrl === true && key.sequence === 'l',
  [Command.CLEAR_INPUT]: (key) => key.ctrl === true && key.sequence === 'c',
  [Command.HOME]: (key) => key.ctrl === true && key.sequence === 'a',
  [Command.END]: (key) => key.ctrl === true && key.sequence === 'e',
  [Command.NAVIGATION_UP]: (key) => key.upArrow === true,
  [Command.NAVIGATION_DOWN]: (key) => key.downArrow === true,
  [Command.HISTORY_UP]: (key) => key.ctrl === true && key.sequence === 'p',
  [Command.HISTORY_DOWN]: (key) => key.ctrl === true && key.sequence === 'n',
  [Command.COMPLETION_UP]: (key) => key.upArrow === true,
  [Command.COMPLETION_DOWN]: (key) => key.downArrow === true,
  [Command.ACCEPT_SUGGESTION]: (key) => key.tab === true,
  [Command.KILL_LINE_RIGHT]: (key) => key.ctrl === true && key.sequence === 'k',
  [Command.KILL_LINE_LEFT]: (key) => key.ctrl === true && key.sequence === 'u',
  [Command.OPEN_EXTERNAL_EDITOR]: (key) => key.ctrl === true && key.sequence === 'x',
  [Command.PASTE_CLIPBOARD_IMAGE]: (key) => key.ctrl === true && key.sequence === 'v',
  [Command.REVERSE_SEARCH]: (key) => key.ctrl === true && key.sequence === 'r',
  [Command.ACCEPT_SUGGESTION_REVERSE_SEARCH]: (key) => key.tab === true,
  [Command.SUBMIT_REVERSE_SEARCH]: (key) => key.return === true,
};